### ISSUE TITLE
[Pipeline]: Upload untagged call turns to skit-labels for annotation.

### ISSUE THREAD

**Issue by ltbringer** [skit-ai/skit-pipelines#1]
We have [skit-labels](https://github.com/skit-ai/skit-labels) that already takes care of getting call turns tagged, and even downloading.
A component around it will be necessary for the basic release of this project.

- We need a component that wraps around skit-labels.
- A pipeline that uploads data to our annotation service.

Take reference from the [commands](https://github.com/skit-ai/skit-labels/blob/master/skit_labels/commands.py) and [cli](https://github.com/skit-ai/skit-labels/blob/master/skit_labels/cli.py).

**Comment by biswaroop1547** [comment]
Also need a component around [skit-auth](https://github.com/skit-ai/skit-auth) for authorization purposes which will also be used in the uploading pipeline.
