### ISSUE TITLE
Moving SLU model evaluation as a seperate component

### ISSUE THREAD

**Issue by harshithere** [skit-ai/skit-pipelines#124]
**Why**
Currently model [evaluation](https://github.com/skit-ai/skit-pipelines/blob/0ea2c0951781b91574cbce38927b3869d73fab1f/skit_pipelines/components/retrain_slu_from_repo/utils.py#L97) is performed as part of the SLU retraining [component](https://github.com/skit-ai/skit-pipelines/tree/a7461db1e35b014759d3b5b9d3c0d872da5cc674/skit_pipelines/components/retrain_slu_from_repo). This makes it difficult to evaluate live models and increases the complexity of the `retrain_slu` codebase. Given we want to add functionality to test model performance without retraining, the current setup is not optimal for that.

**What**
- Move evaluation as a separate component and get confusion matrix/classification report as output from it for both the new trained model and existing model in production
- Move `comparision_report_generator.py` as a component that takes in 2 reports as input and gives the combined report as output

**Success criteria**
The retrain_slu functionality works as now post all these changes

**Comment by deepak-aryak9** [comment]
@harshithere I am taking this up, and I will try to close this soon.
