### ISSUE TITLE
uvicorn: command not found

### ISSUE THREAD

**Issue by keshav47** [skit-ai/skit-pipelines#13]
**Describe the Issues**
Getting `bash: line 4: uvicorn: command not found` on running docker-compose up
Error is originating from [this ](https://github.com/skit-ai/skit-pipelines/blob/main/docker-compose.yml#L46) line in docker-compose.yaml

**Comment by biswaroop1547** [comment]
hi @keshav47 can you describe more on how to reproduce this?

**Comment by keshav47** [comment]
On a previously cloned repo, I did the following things:
1) git pull origin main
2) dvc pull && source secrets/env.sh
3) docker-compose up

System:
WSL
Ubuntu 20.04
python 3.10.3

**Comment by keshav47** [comment]
**Issue:**
Was using an older version of  `BASE_IMAGE`, whose pyproject.toml didn't include uvicorn, hence the `uvicorn: command not found` error.

**Reason**
docker-compose.yml pull the docker image from the following env variable
```
BASE_IMAGE="536612919621.dkr.ecr.ap-south-1.amazonaws.com/vernacular-voice-services/ai/kubeflow/ml-pipeline:$(git describe --tags --abbrev=0)"
```
`git describe --tags --abbrev=0` describes the latest tag. Doing `git pull` on a cloned repo doesn't fetch the latest pushed tags, since I had older tag available locally, docker-compose ended up pulling an outdated version of the BASE_IMAGE.

**Fix**
`git  fetch` for pulling the latest tags before running :
- source secrets/env.sh
- docker-compose up



Thanks @biswaroop1547 for the fix.
