### ISSUE TITLE
flow-name based filtering not working in fetch-untagged-calls-dataset

### ISSUE THREAD

**Issue by keshav47** [skit-ai/skit-pipelines#17]
**Issue**
Not able to fetch calls made to a specific flow using the parameter flow-name. 
Fetched calls seemed to include data from all flow inside the client organization.
Ref: [Kubeflow Run](https://kubeflow.skit.ai/_/pipeline/?ns=skit#/runs/details/3af4788b-dcd6-4a51-acdd-840e90d2a791)

**Comment by biswaroop1547** [comment]
this has been fixed, hence closing
