### ISSUE TITLE
[Pipeline]: Build IRR, ERR, WER eval pipelines around eevee

### ISSUE THREAD

**Issue by tanmay17061** [skit-ai/skit-pipelines#18]
We use [eevee](https://github.com/skit-ai/eevee) to generate IRR, ERR and WER metrics on appropriately tagged datasets in charon format. Create pipeline(s) that wraps eevee and automates these evaluations.

**Comment by greed2411** [comment]
irr & eer done.

**Comment by biswaroop1547** [comment]
@tanmay17061 @greed2411 can we close this?
