### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by ltbringer** [skit-ai/skit-pipelines#3]
We need to be able to receive requests from slack and trigger kubeflow pipeline runs.

**Comment by nvinayvarma189** [comment]
Assigning this to myself

**Comment by biswaroop1547** [comment]
for kubeflow pipelines api server -> working on #9 PR

**Comment by ltbringer** [comment]
Covered in [0.1.80](https://github.com/skit-ai/skit-pipelines/releases/tag/0.1.80)
